version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  test-linux:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - run: npm ci
      - run: npm test

  test-macos-m1:
    macos:
      xcode: 16.2.0
      resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run: npm ci
      - run: npm test

  test-windows:
    executor:
      name: win/default
      size: medium
    steps:
      - checkout
      - run: choco install nodejs-lts -y
      - run: npm ci
      - run: npm test

workflows:
  test:
    jobs:
      - test-linux
      - test-macos-m1
      - test-windows
