version: 2.1

jobs:
  test-linux:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run: npm ci
      - run: npm test

  test-macos-m1:
    macos:
      xcode: 16.2.0
      resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run: npm ci
      - run: npm test

  test-windows:
    machine:
      image: windows-server-2019
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            choco install nodejs-lts -y
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test-linux
      - test-macos-m1
      - test-windows
